templates:
  osdcloud:
    PSCommand: ['Start-OSDCloud -Firmware -SkipAutopilot -SkipODT -ZTI -OSVersion "Windows 10" -OSBuild "21H2" -OSEdition "Pro" -OSLanguage "en-gb" -OSLicense "Retail"']

controls:
- SetTimer: ['winpe_start']

#################################################################################################
# Install Windows                                                                               #
#################################################################################################

- template:
  - 'osdcloud'

#################################################################################################
# Install bootloader                                                                            #
#################################################################################################

- PSCommand: ['& X:\Windows\System32\bcdboot.exe C:\Windows /c /v']

#################################################################################################
# Copy files from WinPE to the host for later use                                               #
#################################################################################################

- PSCommand: ['mkdir C:\glazier_cache']

- BuildInfoDump: []

- SetTimer: ['winpe_stop']

#################################################################################################
# Exit WinPE                                                                                    #
#################################################################################################
- ExitWinPE: []
