templates:
  osdcloud:
    PSCommand: ['Start-OSDCloud -Firmware -SkipAutopilot -SkipODT -ZTI -OSVersion "Windows 11" -OSBuild "23H2" -OSEdition "Pro" -OSLanguage "en-gb" -OSLicense "Retail"']

controls:
- SetTimer: ['winpe_start']

#################################################################################################
# Install Windows                                                                               #
#################################################################################################

- template:
  - 'osdcloud'

#################################################################################################
# Install bootloader                                                                            #
#################################################################################################

- PSCommand: ['& X:\Windows\System32\bcdboot.exe C:\Windows /c /v']

# Install the December 2023 cumulative update for the AlwaysOn VPN fix
- UpdateMSU:
  - ['https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/a2fe5398-6f24-46ee-a533-372dc30bfd82/public/windows11.0-kb5039212-x64_2b67855a5e73c7a873e6bdca512c8c106b429196.msu', 'C:\glazier_cache\kb5039212.msu', 'd46934604e355ea9ac61fc1130f8d07ce9b98590ea26847f8af1e14b81182f37']

#################################################################################################
# Copy files from WinPE to the host for later use                                               #
#################################################################################################

- PSCommand: ['mkdir C:\glazier_cache']

- BuildInfoDump: []

- SetTimer: ['winpe_stop']

#################################################################################################
# Exit WinPE                                                                                    #
#################################################################################################
- ExitWinPE: []
