templates:
  osdcloud:
    PSCommand: ['Start-OSDCloud -Firmware -SkipAutopilot -SkipODT -ZTI -OSVersion "Windows 10" -OSBuild "21H2" -OSEdition "Pro" -OSLanguage "en-gb" -OSLicense "Retail"']

controls:
- SetTimer: ['winpe_start']

#################################################################################################
# Install Windows                                                                               #
#################################################################################################

- PSCommand: ['Uninstall-Module -Name OSD -Confirm:$False -Force -Verbose']
- PSCommand: ['Install-Module -Name OSD -RequiredVersion 22.6.22.3 -Confirm:$False -Force -Verbose']

- template:
  - 'osdcloud'

#################################################################################################
# Install bootloader                                                                            #
#################################################################################################

- PSCommand: ['& X:\Windows\System32\bcdboot.exe C:\Windows /c /v']

#################################################################################################
# Prepare MGMT & unattend config                                                                #
#################################################################################################

- pull:
  - ['unattend.xml', 'C:\Windows\Panther\Invoke-OSDSpecialize.xml']

- MkDir: ['C:\MGMT']
- MkDir: ['C:\MGMT\Temp']
- MkDir: ['C:\MGMT\Temp\odt']

- pull:
  - ['MGMT/mgmt-installer-amd64.exe', 'C:\MGMT\mgmt-installer-amd64.exe']
  - ['Office365/officedeploymenttool_15128-20224.exe', 'C:\MGMT\Temp\odt_installer.exe']
  - ['Office365/config.xml', 'C:\MGMT\Temp\odt\a1-config.xml']

#################################################################################################
# Copy files from WinPE to the host for later use                                               #
#################################################################################################

- PSCommand: ['mkdir C:\glazier_cache']

- CopyDir: ['X:\Python', 'C:\Python', true]
- CopyDir: ['X:\glazier', 'C:\glazier', true]
- CopyDir: ['X:\glazier-resources', 'C:\glazier-resources', true]
- pull:
  - ['autobuild.ps1', 'C:\windows\system32\autobuild.ps1']

- BuildInfoDump: []

- SetTimer: ['winpe_stop']

#################################################################################################
# Exit WinPE                                                                                    #
#################################################################################################
- ExitWinPE: []

#################################################################################################
# Enter Host                                                                                    #
#################################################################################################
- SetTimer: ['host_start']

- BuildInfoSave: []

# Launch Glazier with every subsequent reboot
- MultiRegAdd: [
    ['HKCU', 'Software\Microsoft\Windows NT\CurrentVersion\Winlogon', 'Shell', 'powershell.exe -NoProfile -WindowStyle Maximized -NoExit -NoLogo -ExecutionPolicy Bypass -Command & C:\windows\system32\autobuild.ps1', 'REG_SZ'],
    ['HKCU', 'Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', 'NoLogoff', 1, 'REG_DWORD'],
    ['HKCU', 'Software\Microsoft\Windows\CurrentVersion\Policies\System', 'DisableChangePassword', 1, 'REG_DWORD'],
    ['HKCU', 'Software\Microsoft\Windows\CurrentVersion\Policies\System', 'DisableLockWorkstation', 1, 'REG_DWORD'],
  ]

#################################################################################################
# Install Software                                                                              #
#################################################################################################

- PSCommand: ['& C:\MGMT\Temp\odt_installer.exe /extract:C:\MGMT\Temp\odt /quiet /norestart']

- PSCommand: ['& C:\MGMT\Temp\odt\setup.exe /configure C:\MGMT\Temp\odt\a1-config.xml']

- PSCommand: ['& C:\MGMT\mgmt-installer-amd64.exe']

#################################################################################################
# Complete the install                                                                          #
#################################################################################################

- MultiRegAdd: [
    ['HKLM', 'Software\Microsoft\Windows NT\CurrentVersion\Winlogon', 'AutoAdminLogon', '0', 'REG_SZ']
  ]

- Reboot: [10, 'Rebooting to finish host configuration']