templates:
  osdcloud:
    PSCommand: ['Start-OSDCloud -Firmware -SkipAutopilot -SkipODT -ZTI -OSVersion "Windows 11" -OSBuild "23H2" -OSEdition "Pro" -OSLanguage "en-gb" -OSLicense "Retail"']

controls:
- SetTimer: ['winpe_start']

#################################################################################################
# Install Windows                                                                               #
#################################################################################################

#- MkDir: ['X:\OSDCloud']
#- MkDir: ['X:\OSDCloud\Autopilot']
#- MkDir: ['X:\OSDCloud\Autopilot\Profiles']

#- pull:
#  - ['AutopilotConfigurationFile.json', 'X:\OSDCloud\Autopilot\Profiles\AutopilotConfigurationFile.json']

- template:
  - 'osdcloud'

#################################################################################################
# Install bootloader                                                                            #
#################################################################################################

- PSCommand: ['& X:\Windows\System32\bcdboot.exe C:\Windows /c /v']

#################################################################################################
# Handle the initial unattend configuration                                                     #
#################################################################################################

- pull:
  - ['initial/unattend.xml', 'C:\Windows\Panther\Invoke-OSDSpecialize.xml']
  - ['oobe/unattend.xml', 'C:\Windows\system32\sysprep\unattend.xml']

- Execute: [
  ['C:\Windows\System32\reg.exe load HKLM\TempSYSTEM C:\Windows\System32\Config\SYSTEM'],
  ['C:\Windows\System32\reg.exe add HKLM\TempSYSTEM\Setup /v UnattendFile /d C:\Windows\Panther\Invoke-OSDSpecialize.xml /f'],
  ['C:\Windows\System32\reg.exe unload HKLM\TempSYSTEM'],
]

# Add Glazier to the default user profile,
# to work around it not loading properly after booting into autologon.
- MultiPSCommand: [
  ['& C:\Windows\System32\reg.exe load HKLM\TempDefaultUser C:\Users\Default\NTUSER.DAT'],
  ['& C:\Windows\System32\reg.exe add "HKLM\TempDefaultUser\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" /v Shell /t REG_SZ /d "powershell.exe -NoProfile -WindowStyle Maximized -NoExit -NoLogo -ExecutionPolicy Bypass -Command & C:\windows\system32\autobuild.ps1" /f'],
  ['& C:\Windows\System32\reg.exe add "HKLM\TempDefaultUser\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v NoLogoff /t REG_DWORD /d 1 /f'],
  ['& C:\Windows\System32\reg.exe add "HKLM\TempDefaultUser\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableChangePassword /t REG_DWORD /d 1 /f'],
  ['& C:\Windows\System32\reg.exe add "HKLM\TempDefaultUser\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableLockWorkstation /t REG_DWORD /d 1 /f'],
  ['& C:\Windows\System32\reg.exe unload HKLM\TempDefaultUser'],
]

#################################################################################################
# Copy files from WinPE to the host for later use                                               #
#################################################################################################

- PSCommand: ['mkdir C:\glazier_cache']

- CopyDir: ['X:\Python', 'C:\Python', true]
- CopyDir: ['X:\glazier', 'C:\glazier', true]
- CopyDir: ['X:\glazier-resources', 'C:\glazier-resources', true]
- pull:
  - ['autobuild.ps1', 'C:\windows\system32\autobuild.ps1']

#################################################################################################
# Pre-install the January 2024 cumulative update (kb5033375)                                   #
#################################################################################################

- UpdateMSU:
  - ['https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/a9f5de65-91c3-47e7-b987-0ba0468699b8/public/windows11.0-kb5034123-x64_d82c9af459245e90b5bf897f15a72cf810819f31.msu', 'C:\glazier_cache\kb5034123.msu', '349f673b611383d5e2a300d81fb7ad3ceba7226c346993219fecf76c93fc9d67']

- BuildInfoDump: []

- SetTimer: ['winpe_stop']

#################################################################################################
# Exit WinPE                                                                                    #
#################################################################################################
- ExitWinPE: []

#################################################################################################
# Enter Host                                                                                    #
#################################################################################################
- SetTimer: ['host_start']

- BuildInfoSave: []

- Sleep: [30, 'Waiting for Windows Update reboot if required...']

# Remove Glazier from the default user profile.
- MultiPSCommand: [
  ['& C:\Windows\System32\reg.exe load HKLM\TempDefaultUser C:\Users\Default\NTUSER.DAT'],
  ['& C:\Windows\System32\reg.exe delete "HKLM\TempDefaultUser\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" /v Shell /f'],
  ['& C:\Windows\System32\reg.exe add "HKLM\TempDefaultUser\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v NoLogoff /t REG_DWORD /d 0 /f'],
  ['& C:\Windows\System32\reg.exe add "HKLM\TempDefaultUser\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableChangePassword /t REG_DWORD /d 0 /f'],
  ['& C:\Windows\System32\reg.exe add "HKLM\TempDefaultUser\Software\Microsoft\Windows\CurrentVersion\Policies\System" /v DisableLockWorkstation /t REG_DWORD /d 0 /f'],
  ['& C:\Windows\System32\reg.exe unload HKLM\TempDefaultUser'],
]

#################################################################################################
# Install Windows Updates                                                                       #
#################################################################################################

- MultiPSCommand:
  - ['Set-ExecutionPolicy Unrestricted -Force']
  - ['Set-PSRepository -Name PSGallery -InstallationPolicy Trusted']
  - ['Install-Module PSWindowsUpdate -Confirm:$false']
  - ['Start-Service -name wuauserv']

- Sleep: [60, 'Waiting for Windows Update to initialise...']

- MultiPSCommand:
  - ['Get-WindowsUpdate -MicrosoftUpdate -Verbose']
  - ['Install-WindowsUpdate -AcceptAll -Install -MicrosoftUpdate -AutoReboot -Verbose']

- Sleep: [15, 'Waiting for Windows Update reboot if required...']

- MultiPSCommand:
  - ['Set-PSRepository -Name PSGallery -InstallationPolicy Untrusted']
  - ['Set-ExecutionPolicy Restricted -Force']

#################################################################################################
# Install Software                                                                              #
#################################################################################################

- MkDir: ['C:\glazier_cache\install_temp']
- MkDir: ['C:\glazier_cache\install_temp\odt']

- pull:
  - ['Office365/officedeploymenttool_15128-20224.exe', 'C:\glazier_cache\install_temp\odt_installer.exe']
  - ['Office365/config.xml', 'C:\glazier_cache\install_temp\odt\custom-config.xml']

- PSCommand: ['& C:\glazier_cache\install_temp\odt_installer.exe /extract:C:\glazier_cache\install_temp\odt /quiet /norestart']

- PSCommand: ['& C:\glazier_cache\install_temp\odt\setup.exe /configure C:\glazier_cache\install_temp\odt\custom-config.xml']

#################################################################################################
# Configure AutoPilot                                                                           #
#################################################################################################

- pull:
  - ['AutopilotConfigurationFile.json', 'C:\Windows\Provisioning\Autopilot\AutopilotConfigurationFile.json']

#################################################################################################
# Complete the install                                                                          #
#################################################################################################

- MultiPSCommand: [
  ['& C:\Windows\System32\reg.exe delete HKLM\SYSTEM\Setup /v UnattendFile /f'],
]

- Reboot: [10, 'Rebooting before OOBE']

- MultiRegAdd: [
  ['HKLM', 'Software\Microsoft\Windows NT\CurrentVersion\Winlogon', 'AutoAdminLogon', '0', 'REG_SZ']
]

- MultiPSCommand: [
  ['& C:\Windows\System32\reg.exe add "HKLM\Software\Microsoft\Provisioning" /v FirstRunComplete /t REG_DWORD /d 0 /f'],
  ['& C:\Windows\System32\Sysprep\sysprep.exe /oobe /quiet /reboot /unattend:C:\Windows\system32\sysprep\unattend.xml'],
]

- Reboot: [10, 'Rebooting into OOBE']